#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: repo
#+AUTHOR: Andrew M Davis, PhD
#+EMAIL: @reconmaster:matrix.org
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.1 (Org mode 9.1.13)
#+FILETAGS: 気, ki, comp, repo, node
Objective: optimal node interface

#+BEGIN_QUOTE
the stupid content tracker

Torvalds 先生
#+END_QUOTE
* Introduction
With the selection of proper [[https://en.wikipedia.org/wiki/Tool][tools]], it is possible to get useful [[https://en.wikipedia.org/wiki/Work_(physics)][work]]
done.

When utilizing a [[https://en.wikipedia.org/wiki/Computer][computer]], I have found that the ability to modify
your tools to be of great value.

[[https://en.wikipedia.org/wiki/Literate_programming][Literate programming]] has a profound impact on one's interaction with
the hardware cite:knuth_literate_1984. By improving the quality of the
[[https://en.wikipedia.org/wiki/Human][human]]-[[https://en.wikipedia.org/wiki/Machine][machine]] interface, the subsequent quality of the machine's
output is improved. This document is an example piece of [[https://en.wikipedia.org/wiki/Code][code]].

By combining literate programming with sound [[https://en.wikipedia.org/wiki/Unix_philosophy][Unix philosophy]], it is
possible to develop [[https://en.wikipedia.org/wiki/Algorithm][algorithms]] that can solve very useful problems for
[[https://en.wikipedia.org/wiki/Humanity_(virtue)][humanity]].
* Methods
In the course of doing [[https://en.wikipedia.org/wiki/Research][research]], [[https://en.wikipedia.org/wiki/Information][information]] must be manipulated into
a format that is comprehensible to the human [[https://en.wikipedia.org/wiki/Mind][mind]]. The chain by which
this information is processed must be recorded in a transparent way to
ensure [[https://en.wikipedia.org/wiki/Reproducibility][reproducibility]].

This code is designed to be platform independent. That being said, an
[[https://en.wikipedia.org/wiki/Open_source][open-source]] framework makes it far more robust.

The instructions for running this code can be found in the [[file:docs/README.org][documentation]].

\bibliography{resources/ref}
